---
- hosts: localhost
  vars:
    - slack_token: T025L7FG8/B0LS8P62G/PRc429X0u1O5jHxYDzAI0POW
    - user: ubuntu
    - docroot: /home/{{ user }}/app
    - app_env: false
    - app_name: ''
    - cfn_info: ''
    - should_seed: false

  tasks:
    - name: Read CFN_INFO
      set_fact:
        cfn_info: "{{ lookup('ini', 'Stack type=properties file=/home/' + user + '/.CFN_INFO') }}"
      ignore_errors: True

    - name: Notify Slack
      slack:
        token: "{{ slack_token }}"
        msg: "[{{ cfn_info }}] - Project Ansible script starts"
        color: good

    - name: Sync latest scripts
      shell: aws s3 cp s3://cat-provision-config/{{ app_name }}/provision/build.yml /home/{{ user }}/project-ec2

    - name: Sync latest scripts specific for app_env
      shell: aws s3 sync s3://cat-provision-config/{{ app_name }}/provision/{{ app_env }} /home/{{ user }}/project-ec2/{{ app_env }}

    - name: Check if project-ec2/<app_env>/env_additions exists
      stat: path="/home/{{ user }}/project-ec2/{{ app_env }}/env_additions"
      register: env_additions_file

    - name: Get env_additions content
      shell: cat "/home/{{ user }}/project-ec2/{{ app_env }}/env_additions"
      register: env_additions
      when: env_additions_file.stat.exists

    - name: Set env_additions
      blockinfile:
        dest: "{{ docroot }}/.env"
        content: |
          {{ env_additions.stdout }}
      when: env_additions_file.stat.exists

    - name: Notify Slack
      slack:
        token: "{{ slack_token }}"
        msg: "[{{ cfn_info }}] - Running seed. Checking if app is set up."
        color: good
      when: should_seed == 'yes'

    - name: Check if artisan file is there
      stat: path="/home/{{ user }}/app/artisan"
      register: artisan_file

    - name: Notify Slack
      slack:
        token: "{{ slack_token }}"
        msg: "[{{ cfn_info }}] - Skip running seed. App is not set up."
        color: warning
      when: should_seed == 'yes' and not artisan_file.stat.exists

    - name: Run Seed
      shell: "php /home/{{ user }}/app/artisan db:seed"
      register: seed
      when: should_seed == 'yes' and artisan_file.stat.exists

    - name: Notify Slack
      slack:
        token: "{{ slack_token }}"
        msg: "[{{ cfn_info }}] - Seed result: {{ seed.stdout }}"
        color: normal
      when: should_seed == 'yes' and artisan_file.stat.exists

    - name: Notify Slack
      slack:
        token: "{{ slack_token }}"
        msg: "[{{ cfn_info }}] - Restarting Queue"
        color: good
      when: artisan_file.stat.exists

    - name: Restart queue
      shell: "php /home/{{ user }}/app/artisan queue:restart"
      when: artisan_file.stat.exists

    - name: Notify Slack
      slack:
        token: "{{ slack_token }}"
        msg: "[{{ cfn_info }}] - Project Ansible script done"
        color: good
