---
- hosts: localhost:base-ubuntu
  vars:
    - user: ubuntu
    - local: false
    - apt_update: true
    - slack_token: T025L7FG8/B0LS8P62G/PRc429X0u1O5jHxYDzAI0POW
    - cfn_info: ''

  tasks:
    - name: Install starters
      become: yes
      apt: pkg={{ item }} state=installed
      with_items:
        - curl
        - php5-cli
        - git
        - npm
        - nodejs

    - name: fix ubuntu nodejs to node
      become: yes
      file: src=/usr/bin/nodejs dest=/usr/bin/node state=link

    - name: Install Gulp
      become: yes
      shell: npm install --global gulp

    - name: Get Composer
      shell: curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer

    - name: Install packages
      become: yes
      apt: pkg={{ item }} state=installed
      with_items:
        - python-pycurl

    - name: Fix potential broken packages due to updates
      become: yes
      shell: apt-get -f install
      tags:
        - skip_ansible_lint

    - name: Add PPA
      become: yes
      apt_repository: repo='ppa:ansible/ansible' state=present

    - name: Setup Apt and Latest Ansible
      become: yes
      apt: pkg=software-properties-common state=installed

    - name: Update Apt
      become: yes
      apt: update_cache=yes
      when: apt_update

    - name: Install Ansible
      become: yes
      apt: pkg=ansible state=installed
      when: not local

    - name: Install Ansible Host
      become: yes
      copy: src=templates/hosts dest=/etc/ansible/hosts owner=root group=root force=yes directory_mode=yes

    - name: Get Pip
      become: yes
      get_url: url=https://bootstrap.pypa.io/get-pip.py dest=/home/{{ user }} validate_certs=no
      when: not local

    - name: Install Pip
      become: yes
      command: /usr/bin/python /home/{{ user }}/get-pip.py
      when: not local

    - name: Install AWS CLI tools
      become: yes
      command: pip install awscli
      when: not local

    - name: Set Region
      become: yes
      command: aws configure set region us-east-1

  handlers:
    - name: Restart SSHD
      become: yes
      service: name=ssh state=restarted
